global:
  wwwHostDomain: lotterydetection-host-www
  wwwHostUrl: "https://lotterydetection-host-www"
  wwwAngularDomain: lotterydetection-angular-www
  wwwAngularUrl: "https://lotterydetection-angular-www"
  nginxProxyBufferSize: "32k"
  nginxProxyBuffersNumber: "8"
  defaultConnString: "Server=anz-sql,1433;Database=LotteryDetectionDb;User ID=sa;Password=123qweX."
www-host:
  containerImage: "lotterydetection-host"
www-angular:
  containerImage: "lotterydetection-angular"  
dbmigrator:
  containerImage: "lotterydetection-migrator"